name: SoundBrary CI

on:
  push:
    branches:
      - main-dev

  pull_request:
    branches:
      - main-dev

jobs:

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Validar TypeScript
        run: npm run build

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Build Angular
        run: npm run build

      - name: Salvar artefato do build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist